### PR TITLE
Edited pensa-mve to remove algorithms with unfavorable licences

### PR DESCRIPTION
**Pull request by PensaLee**
Instructions as per automap, refer to pensa-recognition issue 324 for full details (this is likely public, so I don't want to write about IP here).

### CODE REVIEW

**Review by pensapav — COMMENTED** [review]
With those deletions, can you post the results of running the unit tests?

**Review by joeliven — APPROVED** [review]
LGTM

**Comment by PensaLee** [comment]
> With those deletions, can you post the results of running the unit tests?

At the risk of showing my ignorance, I'm not sure how to run the unit tests for this repo. @pensapav could I impose on your time for some help doing that at some point?

**Comment by PensaLee** [comment]
make: Entering directory '/home/lee/opt-pr-324/pensa-openmve/tests'
g++ -std=c++11 -pthread -Wall -Wextra -pedantic -Wno-sign-compare -I../libs -I/include  -c -o math/gtest_accum.o math/gtest_accum.cc
g++ -std=c++11 -pthread -Wall -Wextra -pedantic -Wno-sign-compare -I../libs -I/include  -c -o math/gtest_matrix_qr.o math/gtest_matrix_qr.cc
g++ -std=c++11 -pthread -Wall -Wextra -pedantic -Wno-sign-compare -I../libs -I/include  -c -o math/gtest_matrix.o math/gtest_matrix.cc
g++ -std=c++11 -pthread -Wall -Wextra -pedantic -Wno-sign-compare -I../libs -I/include  -c -o math/gtest_defines.o math/gtest_defines.cc
g++ -std=c++11 -pthread -Wall -Wextra -pedantic -Wno-sign-compare -I../libs -I/include  -c -o math/gtest_vector.o math/gtest_vector.cc
g++ -std=c++11 -pthread -Wall -Wextra -pedantic -Wno-sign-compare -I../libs -I/include  -c -o math/gtest_functions.o math/gtest_functions.cc
g++ -std=c++11 -pthread -Wall -Wextra -pedantic -Wno-sign-compare -I../libs -I/include  -c -o math/gtest_matrix_tools.o math/gtest_matrix_tools.cc
g++ -std=c++11 -pthread -Wall -Wextra -pedantic -Wno-sign-compare -I../libs -I/include  -c -o math/gtest_algo.o math/gtest_algo.cc
g++ -std=c++11 -pthread -Wall -Wextra -pedantic -Wno-sign-compare -I../libs -I/include  -c -o math/gtest_quaternion.o math/gtest_quaternion.cc
g++ -std=c++11 -pthread -Wall -Wextra -pedantic -Wno-sign-compare -I../libs -I/include  -c -o math/gtest_geom.o math/gtest_geom.cc
g++ -std=c++11 -pthread -Wall -Wextra -pedantic -Wno-sign-compare -I../libs -I/include  -c -o math/gtest_matrix_svd.o math/gtest_matrix_svd.cc
math/gtest_matrix_svd.cc: In member function ‘virtual void MatrixSVDTest_MatrixBidiagonalizationStandardTest_Test::TestBody()’:
math/gtest_matrix_svd.cc:233:12: warning: variable ‘groundtruth_mat_u’ set but not used [-Wunused-but-set-variable]
     double groundtruth_mat_u[M * M];
            ^~~~~~~~~~~~~~~~~
math/gtest_matrix_svd.cc:269:12: warning: variable ‘groundtruth_mat_v’ set but not used [-Wunused-but-set-variable]
     double groundtruth_mat_v[N * N];
            ^~~~~~~~~~~~~~~~~
g++ -std=c++11 -pthread -Wall -Wextra -pedantic -Wno-sign-compare -I../libs -I/include  -c -o mve/gtest_mesh_io.o mve/gtest_mesh_io.cc
g++ -std=c++11 -pthread -Wall -Wextra -pedantic -Wno-sign-compare -I../libs -I/include  -c -o mve/gtest_image.o mve/gtest_image.cc
g++ -std=c++11 -pthread -Wall -Wextra -pedantic -Wno-sign-compare -I../libs -I/include  -c -o mve/gtest_image_io.o mve/gtest_image_io.cc
g++ -std=c++11 -pthread -Wall -Wextra -pedantic -Wno-sign-compare -I../libs -I/include  -c -o mve/gtest_scene.o mve/gtest_scene.cc
g++ -std=c++11 -pthread -Wall -Wextra -pedantic -Wno-sign-compare -I../libs -I/include  -c -o mve/gtest_image_drawing.o mve/gtest_image_drawing.cc
g++ -std=c++11 -pthread -Wall -Wextra -pedantic -Wno-sign-compare -I../libs -I/include  -c -o mve/gtest_bundle.o mve/gtest_bundle.cc
g++ -std=c++11 -pthread -Wall -Wextra -pedantic -Wno-sign-compare -I../libs -I/include  -c -o mve/gtest_mesh_tools.o mve/gtest_mesh_tools.cc
g++ -std=c++11 -pthread -Wall -Wextra -pedantic -Wno-sign-compare -I../libs -I/include  -c -o mve/gtest_image_tools.o mve/gtest_image_tools.cc
g++ -std=c++11 -pthread -Wall -Wextra -pedantic -Wno-sign-compare -I../libs -I/include  -c -o mve/gtest_image_color.o mve/gtest_image_color.cc
g++ -std=c++11 -pthread -Wall -Wextra -pedantic -Wno-sign-compare -I../libs -I/include  -c -o mve/gtest_view.o mve/gtest_view.cc
g++ -std=c++11 -pthread -Wall -Wextra -pedantic -Wno-sign-compare -I../libs -I/include  -c -o mve/gtest_triangle_mesh.o mve/gtest_triangle_mesh.cc
g++ -std=c++11 -pthread -Wall -Wextra -pedantic -Wno-sign-compare -I../libs -I/include  -c -o mve/gtest_camera.o mve/gtest_camera.cc
g++ -std=c++11 -pthread -Wall -Wextra -pedantic -Wno-sign-compare -I../libs -I/include  -c -o mve/gtest_mesh_info.o mve/gtest_mesh_info.cc
g++ -std=c++11 -pthread -Wall -Wextra -pedantic -Wno-sign-compare -I../libs -I/include  -c -o util/gtest_file_system.o util/gtest_file_system.cc
g++ -std=c++11 -pthread -Wall -Wextra -pedantic -Wno-sign-compare -I../libs -I/include  -c -o util/gtest_aligned_memory.o util/gtest_aligned_memory.cc
g++ -std=c++11 -pthread -Wall -Wextra -pedantic -Wno-sign-compare -I../libs -I/include  -c -o util/gtest_tokenizer.o util/gtest_tokenizer.cc
g++ -std=c++11 -pthread -Wall -Wextra -pedantic -Wno-sign-compare -I../libs -I/include  -c -o util/gtest_endian.o util/gtest_endian.cc
g++ -std=c++11 -pthread -Wall -Wextra -pedantic -Wno-sign-compare -I../libs -I/include  -c -o util/gtest_string.o util/gtest_string.cc
g++ -std=c++11 -pthread -Wall -Wextra -pedantic -Wno-sign-compare -I../libs -I/include  -c -o fssr/gtest_octree_iterator.o fssr/gtest_octree_iterator.cc
g++ -std=c++11 -pthread -Wall -Wextra -pedantic -Wno-sign-compare -I../libs -I/include  -c -o fssr/gtest_iso_octree.o fssr/gtest_iso_octree.cc
g++ -std=c++11 -pthread -Wall -Wextra -pedantic -Wno-sign-compare -I../libs -I/include  -c -o fssr/gtest_mesh_clean.o fssr/gtest_mesh_clean.cc
g++ -std=c++11 -pthread -Wall -Wextra -pedantic -Wno-sign-compare -I../libs -I/include  -c -o fssr/gtest_octree.o fssr/gtest_octree.cc
make: *** No rule to make target 'libgtest_main.a', needed by 'test'.  Stop.
make: Leaving directory '/home/lee/opt-pr-324/pensa-openmve/tests'

**Comment by PensaLee** [comment]
So all the tests look like they are coming out OK. The only slight hiccup is  single object that isn't being used, but this test has the same result in the origin, so I don't think that's anything to be worried about.

**Comment by pensapav** [comment]
> > With those deletions, can you post the results of running the unit tests?
> 
> At the risk of showing my ignorance, I'm not sure how to run the unit tests for this repo. @pensapav could I impose on your time for some help doing that at some point?

Looks like you figured this out... should be as simple as running `make test` inside of the tests folder.

**Review by pensapav — APPROVED** [review]
Tests are happy, I'm happy.

**Pull request merged**
